### ISSUE TITLE
hazelcast-ra version is currently 3.7-SNAPSHOT but still references Hazelcast version 3.6

### ISSUE THREAD

**Issue by juanavelez** [hazelcast/hazelcast-ra#4]
Should the hazelcast version match the version of the hazelcast-ra project? 

```
    <modelVersion>4.0.0</modelVersion>
    <name>hazelcast-ra</name>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-ra</artifactId>
    <version>3.7-SNAPSHOT</version>
    <packaging>pom</packaging>
    <description>Hazelcast In-Memory DataGrid Ra Plugin</description>
    <url>http://www.hazelcast.com/</url>

    <modules>
        <module>hazelcast-jca</module>
        <module>hazelcast-jca-rar</module>
    </modules>

    <properties>
        <!-- needed for checkstyle/findbugs -->
        <main.basedir>${project.basedir}</main.basedir>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- we want to remain java 1.6 compatible -->
        <java.version>1.6</java.version>

        <hazelcast.version>3.6</hazelcast.version>
```

**Comment by mesutcelik** [comment]
Sorry for the confusion @juanavelez ,

`hazelcast-ra` and all other submodules which depend on hazelcast core module have been moved into their own github repositories. That was mainly to have independent release cycles of integration modules in order to increase the agility and better respond to the community.

Indeed, hazelcast dependency version must be 3.6.3 which is latest but hazelcast-ra version will stay 3.7-SNAPSHOT as long as we don't add a new feature to it.

For the current stable hazelcast-ra module, you can refer to [hazelcast repository](https://github.com/hazelcast/hazelcast/tree/maintenance-3.x/hazelcast-ra) but once hazelcast 3.7 is released, all future hazelcast-ra maintenance patches and new features  will be implemented in this repository.

I hope it is clear now.

**Comment by juanavelez** [comment]
@mesutcelik Thanks for the info. Quick quesiton. There is an issue (5667 https://github.com/hazelcast/hazelcast/issues/5667) still in hazelcast that refers to hazecast-ra. If I were to submit the fix (still working with my US employer to sign off on the HCA), when would the next version/release be for hazelcast-ra? Where would the pull request be submitted? hazelcast or hazelcast-ra?

Thanks

**Comment by mesutcelik** [comment]
As it is a new feature, It should be sent to this (hazelcast-ra) repository. Once the PR is merged, we can release a new version of hazelcast-ra right away.

**Comment by juanavelez** [comment]
@mesutcelik I have added a pull request for issue 5667 (https://github.com/hazelcast/hazelcast/issues/5667).

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-ra/pull/5
